### ISSUE TITLE
Rultor is failing in run.sh

### ISSUE THREAD

**Issue by g4s8** [yegor256/rultor#1270]
Rultor started to fail to merge pull requests unexpectedly. It merged all previous PRs successfully, but now it can't do it. I didn't change `.rultor.yml` or docker image since last PRs (which were merged by rultor).

Error:
```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 19810
+ echo '1.67.4 dbdae7b78'
1.67.4 dbdae7b78
+ date
Sun Jul 22 11:03:43 CEST 2018
+ uptime
 11:03:43 up 14 days, 19:47,  0 users,  load average: 0.69, 0.92, 0.94
+ ff=no
+ image=g4s8/rultor:latest
+ rebase=false
+ head_branch=master
./run.sh: line 23: syntax error near unexpected token `('
'cid' file is absent, container wasn't started correctly

```

config `.rultor.yml`:
```yml
docker:
  image: "g4s8/rultor:latest"
env:
  MAVEN_OPTS: "-Xmx1g"
merge:
  script:
    - "mvn clean install -B -Pqulice --quiet"
  fast-forward: "no"
release:
  script:
    - 'command sudo make VERSION=$tag'
architect:
  - "g4s8"
```
