### ISSUE TITLE
sensitive data for RELEASE

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1271]
Let's make it possible to specify a list of sensitive file names for the `release` command. The release should NOT push the branch if those files are present. For example:

```yaml
release:
  sensitive:
    - id_rsa
  script: |
    # some script
```
