### ISSUE TITLE
Rultor doesn't support the multi-lines environment variables

### ISSUE THREAD

**Issue by dgroup** [yegor256/rultor#1285]
1. The .rultor.yml
    ````yml
    architect:
      - dgroup

    readers:
      - "urn:github:1651114"

    docker:
      image: maven:3.6.0-jdk-11

    merge:
      env:
        MAVEN_OPTS: |
          -XX:MaxPermSize=256m
          -Xmx512m
          -Djavax.net.ssl.trustStoreType=JKS
          -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
          -Dorg.slf4j.simpleLogger.showDateTime=true
          -Djavax.net.ssl.trustStore=${JAVA_HOME}/lib/security/cacerts
          -Djavax.net.ssl.trustStorePassword=changeit
        JAVA_HOME: "/docker-java-home"
      script:
        - mvn -Pqulice clean install
    ````
2. The error
   ````bash
    Updating 7b44de8..ffd92cc
    Fast-forward
     .circleci/config.yml  |   1 -
     .rultor.yml           |   1 -
     libs/tagyml-0.1.0.jar | Bin 22586 -> 0 bytes
     pom.xml               |  15 ---------------
     4 files changed, 17 deletions(-)
     delete mode 100644 libs/tagyml-0.1.0.jar
    + docker_when_possible
    + true
    ++ tail -n 1
    ++ sed 's/ /\n/g'
    ++ uptime
    + load=6.43
    ++ bc
    ++ echo 6.43 '>' 30
    + '[' 0 -eq 1 ']'
    + echo 'load average is 6.43, low enough to run a new Docker container'
    load average is 6.43, low enough to run a new Docker container
    + break
    + cd ..
    + '[' -n '' ']'
    + use_image=maven:3.6.0-jdk-11
    + docker pull maven:3.6.0-jdk-11
    3.6.0-jdk-11: Pulling from library/maven
    Digest: sha256:d8ab5ccbffdcf77481ec3eebbb3d801948e196a3f7c46360f2bac42d04eb9386
    Status: Image is up to date for maven:3.6.0-jdk-11
    + grep --quiet '\sdgroup_lazylead_104\s*$'
    + docker ps --filter=status=exited
    + ls -al .
    total 716
    drwx--x--x  3 rultor rultor   4096 Jan  4 04:16 .
    drwxrwxrwt 14 root   root   684032 Jan  4 04:16 ..
    -rw-rw-r--  1 rultor rultor    444 Jan  4 04:16 end.sh
    -rwxrwxr-x  1 rultor rultor    338 Jan  4 04:16 entry.sh
    -rw-rw-r--  1 rultor rultor      4 Jan  4 04:16 pid
    drwxrwxr-x 11 rultor rultor   4096 Jan  4 04:16 repo
    -rwxrwxr-x  1 rultor rultor   7878 Jan  4 04:16 run.sh
    -rw-rw-r--  1 rultor rultor    887 Jan  4 04:16 script.sh
    -rw-rw-r--  1 rultor rultor   8483 Jan  4 04:16 stdout
    ++ pwd
    ++ pwd
    + docker run -t --rm -v /tmp/rultor-x4Ti:/main '( '\''--env=MAVEN_OPTS=-XX:MaxPermSize=256m
    -Xmx512m
    -Djavax.net.ssl.trustStoreType=JKS
    -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djavax.net.ssl.trustStore=${JAVA_HOME}/lib/security/cacerts
    -Djavax.net.ssl.trustStorePassword=changeit
    '\'' '\''--env=JAVA_HOME=/docker-java-home'\'' '\''--env=head=git@github.com:dgroup/lazylead.git'\'' '\''--env=pull_id=104'\'' '\''--env=fork=git@github.com:dgroup/lazylead.git'\'' '\''--env=fork_branch=91'\'' '\''--env=head_branch=master'\'' '\''--env=pull_title=#91: Use io.github.dgroup:tagyml from maven central'\'' '\''--env=author=dgroup'\'' '\''--env=scripts=( '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''MAVEN_OPTS=-XX:MaxPermSize=256m
    -Xmx512m
    -Djavax.net.ssl.trustStoreType=JKS
    -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djavax.net.ssl.trustStore=${JAVA_HOME}/lib/security/cacerts
    -Djavax.net.ssl.trustStorePassword=changeit
    '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''JAVA_HOME=/docker-java-home'\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''head=git@github.com:dgroup/lazylead.git'\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''pull_id=104'\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''fork=git@github.com:dgroup/lazylead.git'\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''fork_branch=91'\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''head_branch=master'\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''pull_title=#91: Use io.github.dgroup:tagyml from maven central'\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''export '\''\'\'''\''\'\''\'\'''\'''\''\'\'''\''author=dgroup'\''\'\'''\''\'\''\'\'''\'''\''\'\'''\'''\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''mvn install:install-file'\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' '\''\'\'''\''mvn -Pqulice clean install'\''\'\'''\'' '\''\'\'''\'';'\''\'\'''\'' )'\'' )' --hostname=docker --privileged --memory=6g --memory-swap=16g --oom-kill-disable --cidfile=/tmp/rultor-x4Ti/cid -w=/main -v /var/run/docker.sock:/var/run/docker.sock --name=dgroup_lazylead_104 maven:3.6.0-jdk-11 /main/entry.sh
    docker: invalid reference format: repository name must be lowercase.
    See 'docker run --help'.
    'cid' file is absent, container wasn't started correctly
     ````
