### ISSUE TITLE
Rultor fails to parse a valid yaml

### ISSUE THREAD

**Issue by Glusk** [yegor256/rultor#1312]
This is the [`.rultor.yml`](https://github.com/Glusk2/sprouts/blob/881ff0ef2fe83ef8b236581cd325e56ba6ad23b0/.rultor.yml) file I am using:
``` yml
architect:
  - Glusk2
docker:
  image: "mingc/android-build-box:1.12.0"
release:
  script:
    - "chmod +x gradlew"
    # Increment versionCode
    - "perl -i.orig -pe '/versionCode/ && s/([0-9]+)/$1+1 . $2/e' android/build.gradle"
    # Strip tag of the "v" prefix
    - "version=${tag#'v'}"
    # Bump project version
    - "./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=$version -Prelease.newVersion=$version-SNAPSHOT"
```
The online parser classifies it as a valid `yml` and parses it [successfully](https://yaml-online-parser.appspot.com/?yaml=architect%3A%0A++-+Glusk2%0Adocker%3A%0A++image%3A+%22mingc%2Fandroid-build-box%3A1.12.0%22%0Arelease%3A%0A++script%3A%0A++++-+%22chmod+%2Bx+gradlew%22%0A++++%23+Increment+versionCode%0A++++-+%22perl+-i.orig+-pe+%27%2FversionCode%2F+%26%26+s%2F(%5B0-9%5D%2B)%2F%241%2B1+.+%242%2Fe%27+android%2Fbuild.gradle%22%0A++++%23+Strip+tag+of+the+%22v%22+prefix%0A++++-+%22version%3D%24%7Btag%23%27v%27%7D%22%0A++++%23+Bump+project+version%0A++++-+%22.%2Fgradlew+release+-Prelease.useAutomaticVersion%3Dtrue+-Prelease.releaseVersion%3D%24version+-Prelease.newVersion%3D%24version-SNAPSHOT%22&type=json). [YAMLlint](http://www.yamllint.com/) also confirms that it is in fact a valid `.yml` file!

However, invoking rultor like this:

> @rultor release, tag=`v0.9.0`

failed with this error message ([full log](http://www.rultor.com/t/20611-542162578)):
```
/home/r/script.sh: line 9: unexpected EOF while looking for matching `}'
```
