### ISSUE TITLE
Does Rultor support env variable in script?

### ISSUE THREAD

**Issue by RoRoche** [yegor256/rultor#1338]
Here is the Gradle command I want to perform while releasing:

```yml
release:
  script: |
    git commit --allow-empty -am "${tag}"
    ./gradlew -PnewVersion="${tag}" publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
```

How to pass these secrets to Rultor? Via `settings.xml`?
