### ISSUE TITLE
Pre release `false` doesn't work.

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1758]
I have the next rultor [configuration](https://github.com/volodya-lombrozo/jtcop/blob/main/.rultor.yml) in my project:
```yaml
architect:
  - volodya-lombrozo
docker:
  image: yegor256/rultor-image:1.13.0
merge:
  script: mvn clean install -Pqulice --errors --batch-mode
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" "-DprocessPlugins=false"
    git commit -am "${tag}"
    mvn clean install -Pqulice --errors --batch-mode
```

As you can see, I've put `pre: false` parameter.

**Expected behaviour:**\
Each new release is latest release
**Actual behaviour:**\
Each new release is pre-release

For example the next release is set as `pre-release`:
https://github.com/volodya-lombrozo/jtcop/releases/tag/1.0.1
Hence, I have to change it manually.
