### ISSUE TITLE
make possible to configure environment vars for all commands

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#537]
Let's make it possible to do something like this:

``` yaml
env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
merge:
  script:
    - "..."
```

In this case `MAVEN_OPTS` should be available for `merge` command.
