### ISSUE TITLE
"install" configuration

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#539]
Let's make it possible to configure pre-script command to be executed before every script:

``` yaml
install:
  - bundle install
merge:
  script:
    - jekyll build
deploy:
  script
    - jekyll build
```

`bundle install` should be executed both before merging and deploying
