### ISSUE TITLE
comment in script breaks execution flow

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#593]
This configuration won't work:

``` yaml
deploy:
  script: |
    echo "first"
    # some comment
    echo "second"
```

We won't see the `second` text.
