### ISSUE TITLE
attach binaries to Github releases

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#662]
Let's make it possible to attach binaries to Github releases. For example, in `.rultor.yml`:

```yaml
release:
  artifacts:
    - "target/rultor-${tag}.jar"
```

Rultor should get that `target/rultor-${tag}.jar` file and attach it as a binary artifact to the Github release created.
