### ISSUE TITLE
configurable SSH

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#665]
Let's make ssh configurable via `.rultor.yml`, like this:

``` yaml
ssh:
  host: test.example.com
  port: 22
  key: ./keys/id_rsa
  login: test
```

File `./keys/id_rsa` has to contain a private SSH key.
