### ISSUE TITLE
Rultor and AppVeyor

### ISSUE THREAD

**Issue by micdenny** [yegor256/rultor#722]
I'm trying to test Rultor in a test project written in .net that's already configured on AppVeyor for build.

Is possible to trigger the AppVeyor build using Rultor?

**Comment by yegor256** [comment]
@micdenny We don't support Windows platform at the moment. Simply because Docker doesn't work on Windows. However, I think it's a good idea to make Rultor configurable so that it triggers a build somewhere (on appveyor, for example) instead of running it on its own. Maybe something like this (`.rultor.yml`):

```yaml
release:
  appveyor:
    api_key: 12345678
    # maybe some other params
```

What do you think?

**Comment by micdenny** [comment]
@yegor256 Damn, that could be a great idea!! :smile: 

AppVeyor has a complete [REST Api](http://www.appveyor.com/docs/api) with also the support for schedule a build of a [specific branch](http://www.appveyor.com/docs/api/projects-builds#start-build-commit) or from a [pull request](http://www.appveyor.com/docs/api/projects-builds#start-build-pr).

I would like to help you, but I'm a duffer in Java, at least I would need some advice where to look in the source code to start from.

**Comment by yegor256** [comment]
@micdenny thanks for offering help! I think we'll do it ourselves and you will help us to test this new feature. I think, this will be the right format of the config:

```yaml
services:
  appveyor:
    key: ./appveyor.key # the key is in the file
  travis:
    key: ./travis.key  

deploy:
  services: 
    - appveyor
    - travis
  script:
    # some deploy script

release:
  services:
    - appveyor
  script:
    # some release script
```

So, the first section `services` will configure the connections with them. And then, in other sections we can use them.

**Comment by alex-palevsky** [comment]
@maurezen the task is yours,go ahead

**Comment by micdenny** [comment]
:+1:  great guys! As soon as deployed, I will test it on this [test repo](https://github.com/micdenny/TestingCI)

**Comment by maurezen** [comment]
@yegor256 @micdenny maybe I'm not reading this attentively enough, but what exactly should I do here? The scope of changes needed is not clear to me.

**Comment by yegor256** [comment]
@maurezen it's a new feature, which you have to introduce. Do you understand how this feature should work? If not, I'm ready to explain.

**Comment by maurezen** [comment]
@yegor256 can't say that I clearly understand. Please explain.

**Comment by yegor256** [comment]
@maurezen when we start to process a "request", we check the existence of `services` element in the request configuration. For example, we start a new "deploy" request:

```yaml
deploy:
  services:
    - appveyor
  script:
    echo "deploy works!"
```

Before we run that `echo` script, we should start a build in appveyor and wait for its result. When/if it succeeds, we go for the script. If it fails, we don't try to run the script, we just show the reason of failure in our log. Something like:

```
appveyor build #234 failed, see its full log at http://ci.appveyor.com/234
no reason to continue
```
