### ISSUE TITLE
Feature request: Use .travis.yml when no .rultor.yml

### ISSUE THREAD

**Issue by caarlos0** [yegor256/rultor#781]
The structures of `.travis.yml` and `.rultor.yml` are similiar if you just want to use the default commands (merge, release).

Wouldn't it be nice if we fallback to `.travis.yml` instructions when `.rultor.yml` is not available?

**Comment by yegor256** [comment]
@caarlos0 sounds like a very good idea. but I don't like to fall back silently. how about this instead:

```yaml
merge:
  script: @travis
```

If we see this `@travis` instead of a proper script we understand that the script is in `.travis.yml`. this will allow our users to avoid code duplication. what do you think?

**Comment by caarlos0** [comment]
Fair enough. It would be a really nice to have..

**Comment by velo** [comment]
FWIW, shippable yml has same syntax =D

**Comment by yegor256** [comment]
@caarlos0 @velo yes, right, how about we make it compatible with [different systems](http://www.yegor256.com/2014/10/05/ten-hosted-continuous-integration-services.html), incl travis, shippable, wrecker, etc. something like this:

```
merge:
  script: @wrecker
```

**Comment by caarlos0** [comment]
@yegor256 that would be awesome!

**Comment by caarlos0** [comment]
also, compose the script. eg:

```yml
merge:
  script:
    - apt-get install something that travis already have but rultor have not
    - @travis
```

What do you think?

**Comment by yegor256** [comment]
@caarlos0 well, this makes the situation much more complex. we will have to parse the script and find that `@*` lines and replace them with something...  and this has to be done by `bash`, while the script is already running..

**Comment by caarlos0** [comment]
@yegor256 true that...

It might be easier to provide a `before_install` or something like that...

I think this will need a little bit more of planning.

Travis supports before/after install and other phases, so, they should be ran in a specific order by rultor..

I believe that the first thing to do is decide what will work and what will not, and what will be done in the "first" version... what do you think?

**Comment by yegor256** [comment]
@caarlos0 yes, it's better to discuss first, to get the right implementation in the first place. this is what I have in mind, as a full picture:

```yaml
install: @travis # will take pre_install + install + post_install from travis
merge:
  script: @travis # will take script from travis
```

and that's it. nothing fancy, just basic and simple. if someone wants something more complex, we can't help. what do you think?
