### ISSUE TITLE
RFE: Custom commands

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#870]
Effectively, merge and deploy are simple scriptable things. You probably do that already internally modular, i.e. have a single script or entry point for a command but that could be exposed to the user. What I'm thinking of is something like being able to place arbitrary things in the yml like:

```
rebase:
  help: "Rebases the branch of the current pull request onto master."
  parameter: TARGET
  merge-before: false
  push-after: force
  script:
    - git rebase $(TARGET)
```

And something like `rultor help rebase` (omitting @ to not summon rultor) would show the specified help text and the parameters similar to a man page.

Just a raw idea but I think it may add a lot of flexibility to rultor. Plus I'd love to have a rebase command so we can retrigger review and CI when master moved on the base of our PR in ff-based workflow ;)

**Comment by sils1297** [comment]
I can imagine a lot of cool stuff with such a feature. One should probably be able to set a success/fail message too:

```
thanks:
  success: "You're welcome!"
  fail: "Very kind, but you can yhank me after this got merged."
  script:
    - # TODO, check if this commit is already on master
```
