### ISSUE TITLE
RFE: No merge script

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#878]
It would be nice if rultor could just leave the CI stuff to the CI servers (see https://github.com/yegor256/rultor/issues/869) and run with *no script at all*.

**Comment by yegor256** [comment]
@sils1297 you can do something like this:

```yaml
merge:
  script:
    echo "nothing"
```
