### ISSUE TITLE
Refuse release dependent on bug number

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#916]
It would be nice to be able to be able to configure rultor like this:

```
release:
  requirements:
    bugs:
      label: bug
      max: 0
```

to let rultor use the github API to check if there are more than "0" bugs labelled with "bug" and refuse the release if there are any bugs that would actually be released.

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@sils1297 good idea, but I would rather make the configuration simpler, for example:

```yaml
release:
  required:
    label-absent: bug
    arg-matches: tag [0-9\.]+
    label-max: minor-bug
```

What do you think?
