### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by xeboc** [yegor256/rultor#936]
I've been looking through the documentation at http://doc.rultor.com/reference.html and I can't find any reference to a couple of strings in .rultor.yml that are used for yegor256/rultor:

```
merge:
  fast-forward: only
  rebase: true

release:
  pre: false
```

Also, rultor/src/jekyll/_posts/2014/jul/2014-07-14-commands.md makes reference to the commands: Lock, Unlock, and Stop, which are not mentioned in the main documentation.

Would you please improve the documentation on these?  Thank you!
